[package]
name = "mp3-player-tauri"
version = "1.3.0"
edition = "2021"

[lib]
name = "mp3_player_tauri_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[package.metadata]
resources = []

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1"
