server.port=8111

# Letras
mp3.lyrics.base-url=https://www.letras.mus.br
mp3.lyrics.user-agent=Mozilla/5.0
mp3.lyrics.search-path=/
mp3.lyrics.timeout-connect=8000
mp3.lyrics.timeout-fetch=15000

# Capas de Album
mp3.cover.user-agent=Mozilla/5.0 (compatible; MP3Player/1.0)
mp3.cover.itunes-url=https://itunes.apple.com/search?entity=album&limit=1&term=
mp3.cover.deezer-url=https://api.deezer.com/search/album?limit=1&q=
mp3.cover.timeout-connect=15000
mp3.cover.timeout-download=25000